################################################################################################################################################
## Virtual Adobe user_sync setup script
## VM: https://app.vagrantup.com/senglin/boxes/win-10-enterprise-vs2015community
################################################################################################################################################

## Primary machine setup
Vagrant.configure("2") do |config|

 #  config.vm.box = "senglin/win-10-enterprise-vs2015community"             # Standard Windows 10
 #  config.vm.box = "inclusivedesign/windows81-eval-x64"
 	config.vm.box = "danimaetrix/win10-prof-x64"
	#config.vm.box = "opentable/win-7-professional-amd64-nocm"
 
  config.vbguest.auto_update = false
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.gui = false
  end

end




