
## Primary machine setup
Vagrant.configure("2") do |config| 

  # config.vm.box = "danimaetrix/prft-2012r2-standard-ads"				   # Active Directory
  # config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"             # No bells or whistles - standard 2012r2 server without updates or added software (With GUI)
  config.vm.box = "danimaetrix/2012R2-demo-server"                         # Finished 2012r2 server meant for demo of UST and other testing+

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.gui = false
  end
end

