################################################################################################################################################
## Virtual Adobe user_sync setup script
################################################################################################################################################



## Primary machine setup
Vagrant.configure("2") do |config|

    config.vm.box = "AndrewDryga/vagrant-box-osx"
    config.ssh.insert_key = false
    config.vm.synced_folder ".", "/vagrant", disabled: true #type: "rsync" # or "rsync"
    config.vm.synced_folder "../Scratch Directory", "/scratch", disabled: true #type: "rsync" # or "rsync"
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.gui = false
    end


end

