###############################################################################################################################################
## Virtual Adobe user_sync setup script
################################################################################################################################################



## Primary machine setup
Vagrant.configure("2") do |config|

  # config.vm.box = "debian/wheezy64"
  # config.vm.box = "debian/contrib-jessie64"
  config.vm.box = "generic/debian9"

  config.vm.synced_folder "G:/Repositories/microservice-picam", "/scratch"
  config.vbguest.auto_update = false
  config.vm.boot_timeout = 600
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]

  end
  config.ssh.insert_key = false

end

