################################################################################################################################################
## Virtual Adobe user_sync setup script
################################################################################################################################################



## Primary machine setup
Vagrant.configure("2") do |config|

    # config.vm.box = "f500/ubuntu-lucid64"                 # Ubuntu 10.04
    # config.vm.box = "3dox/ubuntu-oneiric"                 # Ubuntu 11.04
    # config.vm.box = "hashicorp/precise64"                 # Ubuntu 12.04
    # config.vm.box = "rafaelrosafu/raring64-vanilla"       # Ubuntu 13.04
    # config.vm.box = "ubuntu/trusty64"                     # Ubuntu 14.04
    # config.vm.box = "bento/ubuntu-14.04"                  # Ubuntu 14.04
    # config.vm.box = "wzurowski/vivid64"                   # Ubuntu 15.04
    # config.vm.box = "geerlingguy/ubuntu1604"              # Ubuntu 16.04
    # config.vm.box = "mrlesmithjr/zesty64"                 # Ubuntu 17.04
    # config.vm.box = "ubuntu/bionic64"                     # Ubuntu 18.04

	config.vm.box = "janihur/ubuntu-1604-lxde-desktop"
	
    config.ssh.insert_key = false
	config.vbguest.auto_update = false
    config.vm.synced_folder "../../Scratch Directory", "/scratch"
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
    end


end

