
## Primary machine setup
Vagrant.configure("2") do |config|
 
 	config.vm.box = "opentable/win-2008r2-standard-amd64-nocm"
 
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.gui = false
  end
end

