################################################################################################################################################
## Virtual Adobe user_sync setup script
################################################################################################################################################



## Primary machine setup
Vagrant.configure("2") do |config|

  #config.vm.box = "danimaetrix/openSUSE-Leap-42.3"
  #config.vm.box = "opensuse/openSUSE-42.2-x86_64"
 # config.vm.box = "webhippie/opensuse-13.2"
  config.vm.box = "bento/opensuse-leap-42.1"

    config.vbguest.auto_update = false
    config.vm.boot_timeout = 600
    config.vm.provider "virtualbox" do |v|
      v.customize ["modifyvm", :id, "--memory", 2048]
      v.customize ["modifyvm", :id, "--cpus", 2]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    end

    config.ssh.insert_key = false

end

