################################################################################################################################################
## https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=danimaetrix
################################################################################################################################################

## Primary machine setup
Vagrant.configure("2") do |config|

  config.vm.box = "danimaetrix/vista-sp2-x64"
 

  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 2048]
    v.customize ["modifyvm", :id, "--cpus", 2]
    v.customize ["modifyvm", :id, "--vram", "256"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.gui = false
  end

end




